/*
 * AvaTax Software Development Kit for JavaScript
 *
 * (c) 2004-2022 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    https://www.apache.org/licenses/LICENSE-2.0
 * @link       https://github.com/avadev/AvaTax-REST-V2-JS-SDK
 */

/**
 * Regenerates lib/enums/index.ts and lib/models/index.ts from the .ts files
 * actually present in those directories.
 *
 * These barrel files used to be maintained by hand / by the upstream code
 * generator, and drifted every release: new enums and models landed on disk
 * without a matching `export *` line, so any model importing them from
 * '../enums/index' failed to compile. Deriving the barrel from the directory
 * makes that class of breakage impossible.
 *
 *   node scripts/sync-barrels.js           rewrite the barrels
 *   node scripts/sync-barrels.js --check   exit 1 if they are out of date
 */

const fs = require('fs');
const path = require('path');

const HEADER = [
  '/*',
  ' * AvaTax Software Development Kit for JavaScript',
  ' *',
  ' * (c) 2004-2022 Avalara, Inc.',
  ' *',
  ' * For the full copyright and license information, please view the LICENSE',
  ' * file that was distributed with this source code.',
  ' *',
  ' * @author     Jonathan Wenger <jonathan.wenger@avalara.com>',
  ' * @author     Sachin Baijal <sachin.baijal@avalara.com>',
  ' * @copyright  2004-2018 Avalara, Inc.',
  ' * @license    https://www.apache.org/licenses/LICENSE-2.0',
  ' * @link       https://github.com/avadev/AvaTax-REST-V2-JS-SDK',
  ' *',
  ' * This file is generated by scripts/sync-barrels.js -- do not edit by hand.',
  ' * Add a .ts file to this directory and run `npm run sync-barrels`.',
  ' */',
  '',
  ''
].join('\n');

const DIRS = [
  path.join('lib', 'enums'),
  path.join('lib', 'models')
];

function render(dir) {
  const names = fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts')
    .map(f => path.basename(f, '.ts'))
    .sort((a, b) => a.localeCompare(b, 'en'));

  return HEADER + names.map(n => `export * from './${n}';`).join('\n') + '\n';
}

const check = process.argv.includes('--check');
let stale = 0;

for (const dir of DIRS) {
  const target = path.join(dir, 'index.ts');
  const next = render(dir);
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';

  if (current === next) {
    continue;
  }

  if (check) {
    console.error(`${target} is out of date.`);
    stale++;
  } else {
    fs.writeFileSync(target, next);
    console.log(`${target} updated.`);
  }
}

if (check && stale > 0) {
  console.error('\nBarrel files are out of date. Run `npm run sync-barrels` and commit the result.');
  process.exit(1);
}

if (check) {
  console.log('Barrel files are up to date.');
}
